version: '3'
services:
  postgres:
    container_name: nest_starter_postgres
    image: postgres:12
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    networks:
      - nestjs_starter_network
networks:
  nestjs_starter_network:


